name = "teste"
main = "worker.js"
compatibility_date = "2026-01-09"

[[r2_buckets]]
binding = "R2_TESTE"
bucket_name = "teste"

[ai]
binding = "AI"

[triggers]
crons = ["*/7 * * * *"]

[[routes]]
pattern = "teste.adamdh7.org/*"
