name = "teste"
main = "worker.js"
compatibility_date = "2026-01-09"

[[r2_buckets]]
binding = "teste"
bucket_name = "teste"

[ai]
binding = "AI"

[triggers]
crons = ["*/7 * * * *"]

routes = [
  "teste.adamdh7.org/*"
]
